---
title: "Assignment 2"
author: "Summer Liu"
date: "9/16/2020"
output: html_document:
  toc: true
  toc_float: true
---

# Data Load
```{r}
library(ggplot2)
library(dplyr)
library(sf)
library(rnaturalearth)
library(tidyverse)
library(tidycensus)
library(ggspatial)
library(cartogram)
library(ggthemes)
library(rgeos)
library(cartogram)
library(readr)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, warning = FALSE, results = "hide", message = FALSE)
```

## Load the World map
```{r}
world <- ne_countries(scale = 50, returnclass = "sf") 

world_map <- ggplot(world) +
  geom_sf() +
  theme_bw()

world_map
```
## Load USA Map
```{r}
USA_map <- ne_states(country = "United States of America", 
                       returnclass = "sf") %>%
    filter(name != "Alaska",
         name != "Hawaii")

US_map <- ggplot(USA_map) +
  geom_sf() +
  theme_bw()

US_map +
  annotation_scale()

```
### Map Projections
```{r}
USA_EPSG2007 <- "+proj=lcc +lat_1=42.68333333333333 +lat_2=41.71666666666667 +lat_0=41 +lon_0=-71.5 +x_0=200000.0001016002 +y_0=750000 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs"

USA_ESPG3355 <- "+proj=tmerc +lat_0=30 +lon_0=31 +k=1 +x_0=615000 +y_0=810000 +ellps=helmert +towgs84=-146.21,112.63,4.05,0,0,0,0 +units=m +no_defs"

USA_ESRI102140 <- "+proj=tmerc +lat_0=22.31213333333334 +lon_0=114.1785555555556 +k=1 +x_0=836694.05 +y_0=819069.8 +ellps=intl +units=m +no_defs"
```

### USA_EPSG2007
```{r USA_EPSG2007}
ggplot(USA_map) +
  geom_sf() +
  coord_sf(crs = USA_EPSG2007) +
  theme_bw()
```

```{r USA_ESPG3355}
ggplot(USA_map) +
  geom_sf() +
  coord_sf(crs = USA_ESPG3355) +
  theme_bw()
```
```{r USA_ESRI102140}
ggplot(USA_map) +
  geom_sf() +
  coord_sf(crs = USA_ESRI102140) +
  theme_bw()
```
#### Load COVID DATA FOR 07-07-20

```{r}
states_transformed <- USA_map %>%
  st_transform(crs = USA_EPSG2007)

urlfile="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports_us/07-07-2020.csv"

Covid_data_070720 <- read.csv(url(urlfile))
head(Covid_data_0707)

covid_states_070720 <-states_transformed %>%
  left_join(Covid_data_070720, by = c("name" = "Province_State")) %>%
  mutate(pop = 100000 * Confirmed / Incident_Rate) %>%
  select(name, pop, Confirmed, Deaths, Recovered, Active, People_Tested)
```

##### Map Visualization
```{r Rivsed based on Carole's code}
ggplot(covid_states_070720, aes(fill = Confirmed)) +
  geom_sf(color = "lightblue") +
  scale_fill_viridis_c(
    guide = "colourbar", aesthetics = "fill", 
    name = "Number of\nConfirmed cases of\nCOVID-19 as of\nJuly 7, 2020",
    breaks = seq(100000, 500000, by = 100000),
    labels = formatC(seq(100000, 500000, by = 100000), 
                     big.mark = ",", format = "f", digits = 0)) +
  theme_map() +
  theme(legend.background = element_blank())
```

```{r Revised based on Carole's code}
covid_proportional_symbol_map <- covid_states_070720%>%
  st_centroid()

ggplot(states_transformed) +
  geom_sf(fill = NA, color = "brown") +
  geom_sf(data = covid_proportional_symbol_map, 
          aes(size = Deaths),
          alpha = 0.7, color = "orange") +
  scale_size_continuous(name = "Number of death\nCOVID-19 cases as of\nJuly 7, 2020",
    breaks = seq(10000, 50000, by = 10000),
    labels = formatC(seq(10000, 50000, by = 10000), 
                     big.mark = ",", format = "f", digits = 0),
    range = c(0, 25)) +
  theme_classic()
```
```{r Revised based on Carole's code}
covid_cartogram_ncont <- covid_states_070720 %>%
  cartogram_ncont("pop")

ggplot(covid_cartogram_ncont, aes(fill = People_Tested)) +
  geom_sf(color = NA) +
  scale_fill_viridis_c(
    name = "Number of\nPeople Tested\nCOVID-19 cases\nas of July 7, 2020",
    breaks = seq(1000000, 5000000, by = 1000000),
    labels = formatC(seq(1000000, 5000000, by = 1000000), 
                     big.mark = ",", format = "f", digits = 0)) +
  theme_map() +
  theme(legend.background = element_blank())
```

```{r tidycensus data mapping visualization}
vars <- load_variables(year = 2018,
                      dataset = "acs5",
                      cache = TRUE)

Wake_Income_2018<- get_acs(state = "NC", county = "Wake", geography = "tract",
                  variables = "B19049_001", geometry = TRUE)
head(Wake)
Wake %>%
ggplot(aes(fill = estimate)) +
  geom_sf(color = NA) +
  coord_sf(crs = USA_EPSG2007) +
  scale_fill_viridis_c(option = "plasma",
                       name = "Median Household Income 2018, Wake County, NC")
```










