---
title: "Assignment 7"
author: "Summer Liu"
date: "10/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(sf)
library(leaflet)
library(htmltools)
library(htmlwidgets)
library(raster)
library(gstat)
library(spatial)
```

```{r}
WakeCountyPlanningJurisdiction <-
  st_read("https://opendata.arcgis.com/datasets/777cf0ce6d0846688ab1f77534e72510_1.geojson", quiet = TRUE) %>%
  dplyr::select(JURISDICTION)

WakeCountyPlanningJurisdiction <- WakeCountyPlanningJurisdiction %>% 
    group_by(JURISDICTION) %>%
    summarise(geometry = sf::st_union(geometry)) %>%
    ungroup()


leaflet(WakeCountyPlanningJurisdiction) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addPolygons(highlightOptions = highlightOptions(fillColor = "green", 
                                                  fillOpacity = 1),
              label = ~JURISDICTION, 
              weight = 1) 

```


```{r}
construction <- read.csv(file = 'construction.csv')
```


```{r}
Wake_Construction <- left_join(WakeCountyPlanningJurisdiction, construction, by="JURISDICTION")


Wake_Construction$label <- 
  paste(Wake_Construction$JURISDICTION, "<br>",
        construction$Grand.Total, " Construction Permits in the area") %>% 
  lapply(htmltools::HTML)

bins <- seq(min(construction$Grand.Total),
            max(construction$Grand.Total), by = 40)
pal <- colorNumeric("viridis", 
                    domain = construction$Grand.Total,
                    na.color = "#00000000") 

leaflet(Wake_Construction) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addPolygons(highlightOptions = highlightOptions(fillOpacity = 1),
              label = ~JURISDICTION,
              fillColor = ~pal(Grand.Total),
              weight = 1, color = "black") %>%

  addLegend(pal = pal, 
            values = ~Grand.Total,
            bins = 5,
            opacity = 0.7, title = "Construction Permits",
            position = "topright")  
```


```{r}
NC_state_plane <- "+proj=lcc +lat_1=34.33333333333334 +lat_2=36.16666666666666 +lat_0=33.75 +lon_0=-79 +x_0=609601.22 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defS"

WGS84 <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

County_points <- st_centroid(
  st_transform(Wake_Construction, crs = NC_state_plane)) %>% 
  st_transform(WGS84)


leaflet(County_points) %>% 
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addCircles(label = ~JURISDICTION,
             fillColor = ~pal(Grand.Total),
             stroke = FALSE, 
             radius = 2000, 
             fillOpacity = 1) %>% 
              
  addLegend(pal = pal, 
            values = ~Grand.Total,
            bins = 5,
            opacity = 0.7, title = "Construction Permits",
            position = "topright")  
```

```{r}
County_pts_sp <- County_points %>%
  st_transform(NC_state_plane) %>%
  filter(!is.na(Grand.Total)) %>% 
  as_Spatial()

County_poly_sp <- Wake_Construction %>%
  st_transform(NC_state_plane) %>%
  filter(!is.na(Grand.Total)) %>% 
  as_Spatial()
```


```{r}
Wake_raster <- raster(County_poly_sp, res=100)
```


```{r}
gs <- gstat(formula=Grand.Total~1, locations=County_pts_sp)
idw_interp <- interpolate(Wake_raster, gs)

idw_interp_clip <- mask(idw_interp, County_poly_sp) 
```


```{r}
leaflet(County_points) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addRasterImage(idw_interp_clip, colors = pal, opacity = 0.8) %>% 
  addLegend(pal = pal, 
            values = ~Grand.Total,
            bins = 5,
            opacity = 0.7, title = "Construction Permits in Wake County",
            position = "topright")
```














